"""create_vector_chunks

Revision ID: 1a1707433d05
Revises: 20260424_000001
Create Date: 2026-05-28 23:31:42.397891
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


# revision identifiers, used by Alembic.
revision = '1a1707433d05'
down_revision = '20260424_000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('vector_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('syllabus_node_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_code', sa.String(), nullable=True),
    sa.Column('year_level', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('chunk_type', sa.String(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('syllabus_json_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vector_chunks_content_code', 'vector_chunks', ['content_code'], unique=False)
    op.create_index('idx_vector_chunks_embedding', 'vector_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_vector_chunks_year_subject', 'vector_chunks', ['year_level', 'subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vector_chunks_year_subject', table_name='vector_chunks')
    op.drop_index('idx_vector_chunks_embedding', table_name='vector_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_vector_chunks_content_code', table_name='vector_chunks')
    op.drop_table('vector_chunks')
    # ### end Alembic commands ###
