"""tutor_v1

Revision ID: 928e2e58469d
Revises: 1a1707433d05
Create Date: 2026-05-30 23:06:25.378537
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '928e2e58469d'
down_revision = '1a1707433d05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.execute(
        """
        INSERT INTO tutors (id, email, name)
        VALUES ('00000000-0000-0000-0000-000000000000', 'dev@mait.local', 'Local Dev')
        ON CONFLICT (id) DO NOTHING
        """
    )
    op.create_table('tutor_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tutor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year_level', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('ability_tier', sa.String(), nullable=False),
    sa.Column('profile_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tutor_classes_subject', 'tutor_classes', ['subject'], unique=False)
    op.create_index('idx_tutor_classes_tutor_id', 'tutor_classes', ['tutor_id'], unique=False)
    op.create_table('chat_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tutor_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['tutor_classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_threads_class_id', 'chat_threads', ['class_id'], unique=False)
    op.create_index('idx_chat_threads_tutor_id', 'chat_threads', ['tutor_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('retrieval_citations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_thread_id', 'messages', ['thread_id'], unique=False)
    op.add_column('documents', sa.Column('tutor_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('class_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('thread_id', sa.UUID(), nullable=True))
    op.create_index('idx_documents_class_id', 'documents', ['class_id'], unique=False)
    op.create_index('idx_documents_thread_id', 'documents', ['thread_id'], unique=False)
    op.create_index('idx_documents_tutor_id', 'documents', ['tutor_id'], unique=False)
    op.create_foreign_key('fk_documents_tutor_id_tutors', 'documents', 'tutors', ['tutor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_documents_class_id_tutor_classes', 'documents', 'tutor_classes', ['class_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_documents_thread_id_chat_threads', 'documents', 'chat_threads', ['thread_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_thread_id_chat_threads', 'documents', type_='foreignkey')
    op.drop_constraint('fk_documents_class_id_tutor_classes', 'documents', type_='foreignkey')
    op.drop_constraint('fk_documents_tutor_id_tutors', 'documents', type_='foreignkey')
    op.drop_index('idx_documents_tutor_id', table_name='documents')
    op.drop_index('idx_documents_thread_id', table_name='documents')
    op.drop_index('idx_documents_class_id', table_name='documents')
    op.drop_column('documents', 'thread_id')
    op.drop_column('documents', 'class_id')
    op.drop_column('documents', 'tutor_id')
    op.drop_index('idx_messages_thread_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_chat_threads_tutor_id', table_name='chat_threads')
    op.drop_index('idx_chat_threads_class_id', table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index('idx_tutor_classes_tutor_id', table_name='tutor_classes')
    op.drop_index('idx_tutor_classes_subject', table_name='tutor_classes')
    op.drop_table('tutor_classes')
    op.drop_table('tutors')
    # ### end Alembic commands ###
